"""empty message

Revision ID: 3b77d54c1275
Revises: None
Create Date: 2016-10-14 11:54:17.823608

"""

# revision identifiers, used by Alembic.
revision = '3b77d54c1275'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.alter_column('items', 'opened_at',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.add_column('users', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirmed')
    op.alter_column('items', 'opened_at',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.create_table('migrate_version',
    sa.Column('repository_id', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', mysql.TEXT(), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
